# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1123, 865)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_img/高科技数码芯片.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-image: url(:/G:/workdate/python/car_contral/ui_img/IMG_20220716_022025.jpg);")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(90, 110, 951, 691))
        self.frame.setStyleSheet("background-image: url(:/2/2.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 440, 81, 71))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 310, 81, 71))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 310, 81, 71))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 310, 81, 71))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 190, 81, 71))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(490, 140, 391, 51))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(490, 230, 391, 51))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(490, 320, 391, 51))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(490, 420, 391, 51))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(490, 510, 391, 51))
        self.pushButton_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"黑体\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(30, 640, 401, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(510, 640, 401, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 70, 721, 71))
        self.label.setStyleSheet("background-image: url(:/2/2.png);")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "智能巡检小车远程监控平台"))
        self.pushButton_2.setText(_translate("Form", "后退"))
        self.pushButton_3.setText(_translate("Form", "右拐"))
        self.pushButton_4.setText(_translate("Form", "左拐"))
        self.pushButton_5.setText(_translate("Form", "停止"))
        self.pushButton_6.setText(_translate("Form", "前进"))
        self.pushButton_7.setText(_translate("Form", "智能远程控制"))
        self.pushButton_8.setText(_translate("Form", "智能巡检行人安全距离"))
        self.pushButton_9.setText(_translate("Form", "智能巡检口罩佩戴规范"))
        self.pushButton_10.setText(_translate("Form", "智能人体姿态交互"))
        self.pushButton_11.setText(_translate("Form", "关闭"))
        self.lineEdit.setText(_translate("Form", "状态提醒："))
        self.lineEdit_2.setText(_translate("Form", "输出："))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">智能巡检小车远程监控平台</span></p></body></html>"))
import ttt_rc
import car_contral_rc
